### ISSUE TITLE
Corrigir as abas em minhas declarações

### ISSUE THREAD

**Issue by Everbero** [Nocs-lab/inbcm-public-frontend#24]
Ao acessar um item, não está configurada a aba ativa em "minhas declarações" quando apenas 1 tipo de declaração existir da declaração.

**Comment by fabioprocopio** [comment]
@thfields possivelmente, o motivo desse _bug_ é o fato de a declaração não ter os 03 (três) tipos de bens vinculados a ela. Verificar a condição que está implementada para carregar a tela com os dados exibidos.

**Comment by thfields** [comment]
Até o momento, realizei testes tanto localhost na branch development quanto no ambiente de desenvolvimento e as abas estiveram todas colapsadas, independente se tem os 3 tipos ou não e se é retificada ou não. Por hora, irei continuar com os testes até conseguir identificar o erro.

**Comment by Everbero** [comment]
@thfields não daria para deixar a primeira aba sempre pré-selecionada?

**Comment by thfields** [comment]
acabei de fazer mais um teste e identifiquei o erro, ele deixa fechado quando não encontra o museologico.

**Comment by thfields** [comment]
Correção enviada para PR: https://github.com/Nocs-lab/inbcm-public-frontend/pull/31
