### ISSUE TITLE
Alterar o nome da prop

### ISSUE THREAD

**Issue by Everbero** [Nocs-lab/inbcm-public-frontend#54]
https://github.com/Nocs-lab/inbcm-public-frontend/blob/1238af6369514f83b918239bb0210599fef06d8b/src/components/MismatchsModal.tsx#L111C14-L111C30

Alterar o nome da propriedade para utilizar a grafia correta.

**Comment by thfields** [comment]
commit da correção: 89e157114852096f3cedb97322713d9364f181d5
