### ISSUE TITLE
Ajustes visuais no dashoboard

### ISSUE THREAD

**Issue by thfields** [Nocs-lab/inbcm-public-frontend#94]
alterar tamanho do título para H2;
incluir os números de quantidade fixo no gráfico;
verificar as fontes;

**Comment by fabioprocopio** [comment]
@thfields , além dessas atividades listadas na issue, incluir também:

Mudar o título da página de "Painel para acompanhamento de itens no acervo" para “Painel analítico”;

**Comment by thfields** [comment]
commit da issue: aec4b7f52773f52b426e797299b1e777003455db
